baseURL = "/"
languageCode = "en-us"
publishDir = "docs"
title = "Sonecu Widgets"
description = "HELLL"
theme = "kube"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "newpixcom" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Examples"
    weight = -100
    url = "/examples/"
[[menu.main]]
    name = "Community"
    weight = -100
    url = "/community/"
