baseURL = "/"
languageCode = "en-us"
title = "Toneco Widgets"
description = "HELLL"
theme = "kube"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "newpixcom" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Example"
    weight = -100
    url = "/example/"
[[menu.main]]
    name = "Showcase"
    weight = -100
    url = "/showcase/"
